name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      NEW_image:
        description: 'New image'
        required: true
        default: ''
      replicas:
        description: 'Number of replicas'
        required: true
        default: ''
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:

  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: |
          whoami
          ssh admin123@40.83.137.235 "powershell -Command Get-ChildItem"
      - name: Update configuration file on vm1
        run: |
          ssh admin123@40.83.137.235 "powershell cat C:\\Users\\admin123\\automation\\hr.txt"
        shell: powershell
